# ~/.config/alacritty/alacritty.toml

[terminal.shell]
program = "/bin/zsh"

[window]
opacity = 0.8
blur = true
padding = { x = 10, y = 10 }
dynamic_title = true

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 12.0

# --- Paleta Catppuccin Mocha ---
[colors.primary]
background = "#1e1e2e" # base
foreground = "#cdd6f4" # text
dim_foreground = "#7f849c" # overlay1
bright_foreground = "#cdd6f4" # text

[colors.cursor]
text = "#1e1e2e" # base
cursor = "#f5e0dc" # rosewater

[colors.vi_mode_cursor]
text = "#1e1e2e" # base
cursor = "#b4befe" # lavender

[colors.selection]
text = "#1e1e2e" # base
background = "#f5e0dc" # rosewater

[colors.normal]
black = "#45475a"   # surface1
red = "#f38ba8"     # red
green = "#a6e3a1"   # green
yellow = "#f9e2af"  # yellow
blue = "#89b4fa"    # blue
magenta = "#f5c2e7" # pink
cyan = "#94e2d5"    # teal
white = "#bac2de"   # subtext1

[colors.bright]
black = "#585b70"   # surface2
red = "#f38ba8"     # red
green = "#a6e3a1"   # green
yellow = "#f9e2af"  # yellow
blue = "#89b4fa"    # blue
magenta = "#f5c2e7" # pink
cyan = "#94e2d5"    # teal
white = "#a6adc8"   # subtext0

# --- Keybindings (Alt + 1-9 para TMUX) ---
[[keyboard.bindings]]
key = "Key1"
mods = "Alt"
chars = "\u001b1"

[[keyboard.bindings]]
key = "Key2"
mods = "Alt"
chars = "\u001b2"

[[keyboard.bindings]]
key = "Key3"
mods = "Alt"
chars = "\u001b3"

[[keyboard.bindings]]
key = "Key4"
mods = "Alt"
chars = "\u001b4"

[[keyboard.bindings]]
key = "Key5"
mods = "Alt"
chars = "\u001b5"

[[keyboard.bindings]]
key = "Key6"
mods = "Alt"
chars = "\u001b6"

[[keyboard.bindings]]
key = "Key7"
mods = "Alt"
chars = "\u001b7"

[[keyboard.bindings]]
key = "Key8"
mods = "Alt"
chars = "\u001b8"

[[keyboard.bindings]]
key = "Key9"
mods = "Alt"
chars = "\u001b9"
